/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Register a new user.
         *
         *     Args:
         *         body: Request with email, name, username, password, and optional phone.
         *         session: Database session via dependency injection.
         *
         *     Returns:
         *         UserResponse: Created user (HTTP 201).
         *
         *     Raises:
         *         HTTPException: 400 if validation fails or username/email already exists.
         */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate a user and return an access + refresh token pair.
         *
         *     Args:
         *         form_data: OAuth2 form with username and password fields.
         *         session: Database session via dependency injection.
         *
         *     Returns:
         *         TokenResponse: Short-lived access token and long-lived refresh token.
         *
         *     Raises:
         *         HTTPException: 401 if credentials are invalid, 429 if rate-limited.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Exchange a valid refresh token for a new access + refresh token pair.
         *
         *     Implements rotation: the presented refresh token is revoked the moment
         *     it's redeemed, valid or not. If a refresh token is presented that was
         *     already revoked (i.e. already redeemed once, or already logged out),
         *     that's a signal it may have been stolen and reused — every refresh
         *     token belonging to that user is revoked, forcing a fresh login on
         *     every device.
         *
         *     Args:
         *         body: The refresh token to redeem.
         *         session: Database session via dependency injection.
         *
         *     Returns:
         *         TokenResponse: New access token and new refresh token.
         *
         *     Raises:
         *         HTTPException: 401 if the token is invalid, expired, or reused.
         */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revoke a refresh token, ending that session.
         *
         *     Silently succeeds even if the token is missing, unknown, or already
         *     revoked — logout should never leak whether a given token was valid.
         *
         *     Args:
         *         body: The refresh token to revoke (no-op if omitted).
         *         session: Database session via dependency injection.
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Categories
         * @description List all categories.
         *
         *     Args:
         *         service: CategoryService instance via dependency injection.
         *
         *     Returns:
         *         list[CategoryResponse]: All categories.
         */
        get: operations["list_categories_api_v1_categories__get"];
        put?: never;
        /**
         * Create Category
         * @description Create a new category.
         *
         *     Args:
         *         body: Request with name and color.
         *         service: CategoryService instance via dependency injection.
         *
         *     Returns:
         *         CategoryResponse: Created category (HTTP 201).
         *
         *     Raises:
         *         HTTPException: 400 if invalid input, 400 if duplicate name.
         */
        post: operations["create_category_api_v1_categories__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Category
         * @description Retrieve a category by name.
         *
         *     Args:
         *         name: Category name to find.
         *         service: CategoryService instance via dependency injection.
         *
         *     Returns:
         *         CategoryResponse: Found category.
         *
         *     Raises:
         *         HTTPException: 404 if category not found.
         */
        get: operations["get_category_api_v1_categories__name__get"];
        put?: never;
        post?: never;
        /**
         * Delete Category
         * @description Delete a category by name.
         *
         *     Args:
         *         name: Category name to delete.
         *         service: CategoryService instance via dependency injection.
         *
         *     Returns:
         *         None (HTTP 204 No Content).
         *
         *     Raises:
         *         HTTPException: 404 if category not found.
         */
        delete: operations["delete_category_api_v1_categories__name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transaction-types/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Transaction Types
         * @description List all transaction types.
         *
         *     Args:
         *         service: TransactionTypeService instance via dependency injection.
         *
         *     Returns:
         *         list[TransactionTypeResponse]: All transaction types.
         */
        get: operations["list_transaction_types_api_v1_transaction_types__get"];
        put?: never;
        /**
         * Create Transaction Type
         * @description Create a new transaction type.
         *
         *     Args:
         *         body: Request with name and is_positive.
         *         service: TransactionTypeService instance via dependency injection.
         *
         *     Returns:
         *         TransactionTypeResponse: Created transaction type (HTTP 201).
         *
         *     Raises:
         *         HTTPException: 400 if validation fails or duplicate transaction type exists.
         */
        post: operations["create_transaction_type_api_v1_transaction_types__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transaction-types/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Transaction Type
         * @description Retrieve a transaction type by name.
         *
         *     Args:
         *         name: Transaction type name to retrieve.
         *         service: TransactionTypeService instance via dependency injection.
         *
         *     Returns:
         *         TransactionTypeResponse: Found transaction type.
         *
         *     Raises:
         *         HTTPException: 404 if transaction type not found.
         */
        get: operations["get_transaction_type_api_v1_transaction_types__name__get"];
        put?: never;
        post?: never;
        /**
         * Delete Transaction Type
         * @description Delete a transaction type by name.
         *
         *     Args:
         *         name: Transaction type name to delete.
         *         service: TransactionTypeService instance via dependency injection.
         *
         *     Returns:
         *         None (HTTP 204 No Content).
         *
         *     Raises:
         *         HTTPException: 404 if transaction type not found.
         */
        delete: operations["delete_transaction_type_api_v1_transaction_types__name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Items
         * @description List all items.
         *
         *     Args:
         *         service: ItemService instance via dependency injection.
         *
         *     Returns:
         *         list[ItemResponse]: All items.
         */
        get: operations["list_items_api_v1_items__get"];
        put?: never;
        /**
         * Create Item
         * @description Create a new item.
         *
         *     Args:
         *         body: Request with name and category_name.
         *         service: ItemService instance via dependency injection.
         *
         *     Returns:
         *         ItemResponse: Created item (HTTP 201).
         *
         *     Raises:
         *         HTTPException: 400 if validation fails or category not found.
         */
        post: operations["create_item_api_v1_items__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Item
         * @description Retrieve an item by ID.
         *
         *     Args:
         *         item_id: Item ID to retrieve.
         *         service: ItemService instance via dependency injection.
         *
         *     Returns:
         *         ItemResponse: Found item.
         *
         *     Raises:
         *         HTTPException: 404 if item not found.
         */
        get: operations["get_item_api_v1_items__item_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Item
         * @description Delete an item by ID.
         *
         *     Args:
         *         item_id: Item ID to delete.
         *         service: ItemService instance via dependency injection.
         *
         *     Returns:
         *         None (HTTP 204 No Content).
         *
         *     Raises:
         *         HTTPException: 404 if item not found.
         */
        delete: operations["delete_item_api_v1_items__item_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Current User Profile */
        get: operations["get_current_user_profile_api_v1_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Current User */
        patch: operations["update_current_user_api_v1_users_me_patch"];
        trace?: never;
    };
    "/api/v1/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User */
        get: operations["get_user_api_v1_users__user_id__get"];
        put?: never;
        post?: never;
        /** Delete User */
        delete: operations["delete_user_api_v1_users__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Current User Data */
        get: operations["export_current_user_data_api_v1_users_me_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Transactions
         * @description List transactions for the authenticated user with optional filters.
         *
         *     Args:
         *         service: TransactionService instance via dependency injection.
         *         current_user: Authenticated user from JWT token.
         *         transaction_type_name: Optional filter by transaction type name.
         *         currency_code: Optional filter by currency code.
         *         date_from: Optional start date filter (ISO 8601).
         *         date_to: Optional end date filter (ISO 8601).
         *         skip: Number of records to skip for pagination.
         *         limit: Maximum number of records to return (max 100).
         *
         *     Returns:
         *         list[TransactionResponse]: Filtered and paginated user transactions.
         */
        get: operations["list_transactions_api_v1_transactions__get"];
        put?: never;
        /** Create Transaction */
        post: operations["create_transaction_api_v1_transactions__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/{transaction_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Transaction */
        get: operations["get_transaction_api_v1_transactions__transaction_id__get"];
        put?: never;
        post?: never;
        /** Delete Transaction */
        delete: operations["delete_transaction_api_v1_transactions__transaction_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/currencies/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Currencies
         * @description List all currencies.
         *
         *     Args:
         *         service: CurrencyService instance via dependency injection.
         *
         *     Returns:
         *         list[CurrencyResponse]: All reference currencies.
         */
        get: operations["list_currencies_api_v1_currencies__get"];
        put?: never;
        /**
         * Create Currency
         * @description Create a new currency.
         *
         *     Args:
         *         body: Request with code, name, and symbol.
         *         service: CurrencyService instance via dependency injection.
         *
         *     Returns:
         *         CurrencyResponse: Created currency (HTTP 201).
         *
         *     Raises:
         *         HTTPException: 400 if validation fails or duplicate currency exists.
         */
        post: operations["create_currency_api_v1_currencies__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/currencies/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Currency
         * @description Retrieve a currency by ISO 4217 code.
         *
         *     Args:
         *         code: ISO 4217 currency code to retrieve.
         *         service: CurrencyService instance via dependency injection.
         *
         *     Returns:
         *         CurrencyResponse: Found currency.
         *
         *     Raises:
         *         HTTPException: 404 if currency not found.
         */
        get: operations["get_currency_api_v1_currencies__code__get"];
        put?: never;
        post?: never;
        /**
         * Delete Currency
         * @description Delete a currency by code.
         *
         *     Args:
         *         code: ISO 4217 currency code to delete.
         *         service: CurrencyService instance via dependency injection.
         *
         *     Returns:
         *         None (HTTP 204 No Content).
         *
         *     Raises:
         *         HTTPException: 404 if currency not found.
         */
        delete: operations["delete_currency_api_v1_currencies__code__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Account */
        post: operations["create_account_api_v1_accounts__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List My Accounts
         * @description List all accounts for the authenticated user.
         *
         *     Args:
         *         service: AccountService instance via dependency injection.
         *         current_user: Authenticated user from JWT token.
         *         skip: Number of records to skip for pagination.
         *         limit: Maximum number of records to return.
         *
         *     Returns:
         *         list[AccountResponse]: Paginated accounts belonging to the user.
         */
        get: operations["list_my_accounts_api_v1_accounts_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Account */
        get: operations["get_account_api_v1_accounts__account_id__get"];
        put?: never;
        post?: never;
        /** Delete Account */
        delete: operations["delete_account_api_v1_accounts__account_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/budgets/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Budget */
        post: operations["create_budget_api_v1_budgets__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/budgets/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List My Budgets
         * @description List all budgets for the authenticated user.
         *
         *     Args:
         *         service: BudgetService instance via dependency injection.
         *         current_user: Authenticated user from JWT token.
         *         skip: Number of records to skip for pagination.
         *         limit: Maximum number of records to return.
         *
         *     Returns:
         *         list[BudgetResponse]: Paginated budgets belonging to the user.
         */
        get: operations["list_my_budgets_api_v1_budgets_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/budgets/{budget_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Budget */
        get: operations["get_budget_api_v1_budgets__budget_id__get"];
        put?: never;
        post?: never;
        /** Delete Budget */
        delete: operations["delete_budget_api_v1_budgets__budget_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Root
         * @description Health check endpoint.
         *
         *     Returns:
         *         dict: Status and current environment.
         */
        get: operations["read_root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccountRequest
         * @description Validates account creation request from client.
         */
        AccountRequest: {
            /** Name */
            name: string;
            /** Account Type */
            account_type: string;
        };
        /**
         * AccountResponse
         * @description Serializes account data in API response to client.
         *
         *     Includes dynamically calculated balance from account service.
         */
        AccountResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Account Type */
            account_type: string;
            /** User Id */
            user_id: number;
            /** Balance */
            balance: number;
        };
        /** Body_login_api_v1_auth_login_post */
        Body_login_api_v1_auth_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /**
         * BudgetRequest
         * @description Validates budget creation request from client.
         */
        BudgetRequest: {
            /** Amount */
            amount: number;
            /** Month */
            month: number;
            /** Year */
            year: number;
            /** Category Name */
            category_name: string;
            /** Currency Code */
            currency_code: string;
        };
        /**
         * BudgetResponse
         * @description Serializes budget data in API response to client.
         */
        BudgetResponse: {
            /** Id */
            id: number;
            /** Amount */
            amount: number;
            /** Month */
            month: number;
            /** Year */
            year: number;
            /** User Id */
            user_id: number;
            /** Category Name */
            category_name: string;
            /** Currency Code */
            currency_code: string;
        };
        /**
         * CategoryRequest
         * @description Validates category creation/update request from client.
         */
        CategoryRequest: {
            /** Name */
            name: string;
            /** Color */
            color: string;
        };
        /**
         * CategoryResponse
         * @description Serializes category data in API response to client.
         */
        CategoryResponse: {
            /** Name */
            name: string;
            /** Color */
            color: string;
        };
        /**
         * CurrencyCreate
         * @description Validates currency creation request from client.
         */
        CurrencyCreate: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Symbol */
            symbol: string;
        };
        /**
         * CurrencyResponse
         * @description Serializes currency data in API response to client.
         */
        CurrencyResponse: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Symbol */
            symbol: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ItemRequest
         * @description Validates item creation request from client.
         */
        ItemRequest: {
            /** Name */
            name: string;
            /** Category Name */
            category_name: string;
        };
        /**
         * ItemResponse
         * @description Serializes item data in API response to client.
         */
        ItemResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Category Name */
            category_name: string;
        };
        /**
         * LogoutRequest
         * @description Request to revoke a refresh token, ending that session.
         */
        LogoutRequest: {
            /** Refresh Token */
            refresh_token?: string | null;
        };
        /**
         * RefreshRequest
         * @description Request to exchange a refresh token for a new token pair.
         */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * TokenResponse
         * @description Access + refresh token pair returned by login and refresh.
         */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /**
         * TransactionRequest
         * @description Validates transaction creation request from client.
         */
        TransactionRequest: {
            /** Item Id */
            item_id: number;
            /** Account Id */
            account_id: number;
            /** Transaction Type Name */
            transaction_type_name: string;
            /** Currency Code */
            currency_code: string;
            /** Value */
            value: number;
            /** Date */
            date?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /**
         * TransactionResponse
         * @description Serializes transaction data in API response to client.
         */
        TransactionResponse: {
            /** Id */
            id: number;
            /**
             * Date
             * Format: date-time
             */
            date: string;
            /** Value */
            value: number;
            /** Transaction Type Name */
            transaction_type_name: string;
            /** Currency Code */
            currency_code: string;
            /** Item Id */
            item_id: number;
            /** Account Id */
            account_id: number;
            /** Notes */
            notes?: string | null;
        };
        /**
         * TransactionTypeRequest
         * @description Validates transaction type creation request from client.
         */
        TransactionTypeRequest: {
            /** Name */
            name: string;
            /** Is Positive */
            is_positive: boolean;
        };
        /**
         * TransactionTypeResponse
         * @description Serializes transaction type data in API response to client.
         */
        TransactionTypeResponse: {
            /** Name */
            name: string;
            /** Is Positive */
            is_positive: boolean;
        };
        /**
         * UserRequest
         * @description Validates user creation/update request from client.
         *
         *     Password is accepted here but never stored or returned in responses.
         */
        UserRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Name */
            name: string;
            /** Username */
            username: string;
            /** Password */
            password: string;
            /** Phone */
            phone?: string | null;
        };
        /**
         * UserResponse
         * @description Serializes user data in API response to client.
         *
         *     Password is intentionally excluded for security.
         */
        UserResponse: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Name */
            name: string;
            /** Username */
            username: string;
            /** Phone */
            phone?: string | null;
        };
        /**
         * UserUpdateRequest
         * @description Partial update payload for a user's own profile. All fields optional.
         */
        UserUpdateRequest: {
            /** Email */
            email?: string | null;
            /** Name */
            name?: string | null;
            /** Username */
            username?: string | null;
            /** Phone */
            phone?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_api_v1_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_categories_api_v1_categories__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponse"][];
                };
            };
        };
    };
    create_category_api_v1_categories__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_category_api_v1_categories__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_category_api_v1_categories__name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_transaction_types_api_v1_transaction_types__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionTypeResponse"][];
                };
            };
        };
    };
    create_transaction_type_api_v1_transaction_types__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionTypeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionTypeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_transaction_type_api_v1_transaction_types__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionTypeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_transaction_type_api_v1_transaction_types__name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_items_api_v1_items__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemResponse"][];
                };
            };
        };
    };
    create_item_api_v1_items__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_item_api_v1_items__item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_item_api_v1_items__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_user_profile_api_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    update_current_user_api_v1_users_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_api_v1_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_api_v1_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_current_user_data_api_v1_users_me_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_transactions_api_v1_transactions__get: {
        parameters: {
            query?: {
                transaction_type_name?: string | null;
                currency_code?: string | null;
                date_from?: string | null;
                date_to?: string | null;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_transaction_api_v1_transactions__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_transaction_api_v1_transactions__transaction_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_transaction_api_v1_transactions__transaction_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_currencies_api_v1_currencies__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrencyResponse"][];
                };
            };
        };
    };
    create_currency_api_v1_currencies__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CurrencyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrencyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_currency_api_v1_currencies__code__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrencyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_currency_api_v1_currencies__code__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_account_api_v1_accounts__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_accounts_api_v1_accounts_me_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_account_api_v1_accounts__account_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_account_api_v1_accounts__account_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_budget_api_v1_budgets__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BudgetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_budgets_api_v1_budgets_me_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_budget_api_v1_budgets__budget_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                budget_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_budget_api_v1_budgets__budget_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                budget_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
